### ISSUE TITLE
Separate Repositories

### ISSUE THREAD

**Issue by Nparte777** [akshat9000/bixby-projects#1]
Instead of Using Multiple Repos why don't you Checkout into new branch for each project? 
Seems more streamlined
I have done it with my web dev repo saves a lot of trouble

**Comment by akshat9000** [comment]
kaise karte hai bhai? idk how

**Comment by Nparte777** [comment]
Don't delete the repos which are separate for now
Just put the files in the a folder which you want to add as seperate branch
And then inside the folder :
git init
git remote add origin 'repo.git'
git checkout -b "new-branch-name"
git add --all
git commit -m 'comment'
git push origin new-branch-name

Do this for each folder and just with new branch names
Remote will be same for all
Let master branch only have your readme but that's upto you

**Comment by Nparte777** [comment]
![Screenshot_20200624-190412503](https://user-images.githubusercontent.com/43001632/85566293-8e0a5400-b64d-11ea-98f7-a122fde9c7e9.jpg)

Mine is like this 
You cen set default branch in branch settings on github

**Comment by akshat9000** [comment]
Thanks bhai try karta hu

**Comment by Nparte777** [comment]
After you are okay how it is , make the redundant branches private/delete them

**Comment by Nparte777** [comment]
If you are on Linux 'gitg'  is very understandable
Windows one I haven't tried
